fun main() {
    val list= DobleLinkedList<Any>()
    list.deleteElement()
    list.deleteElement(0)
    list.getNextElement()
    list.addElementToEnd(2)
    list.addElementToEnd(4)
    list.addElementToEnd(6)
    list.addElementToEnd(8)
    list.addElementToFront(0)
    list.printAllElements()
    list.printAllElementsDesc()
    list.addElementToMiddle(2, 1)
    list.printAllElements()
    list.addElementToMiddle(4, 3)
    list.printAllElements()
    list.addElementToMiddle(8, 7)
    list.printAllElements()
    list.addElementToMiddle(10, 9)
    list.printAllElements()
    list.printAllElements()
    list.deleteElement(0)
    list.deleteElement(8)
    list.printAllElements()
    list.deleteElement(5)
    list.printAllElements()
    list.deleteElement()
    list.printAllElements()
}